version: "3.4"
services:
  gitlab:
    image: registry.gitlab.com/docker233/gitlab:latest
    build: ./gitlab/
    restart: always
    hostname: 'gitlab.local'
    container_name: gitlab-ce
    privileged: true
    depends_on:
      - postgresql
    links:
      - postgresql:postgresql
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        postgresql['enable'] = true
        gitlab_rails['db_username'] = "gitlab"
        gitlab_rails['db_password'] = "gitlab"
        gitlab_rails['db_host'] = "postgresql"
        gitlab_rails['db_port'] = "5432"
        gitlab_rails['db_database'] = "gitlabhq_production"
        gitlab_rails['db_adapter'] = 'postgresql'
        gitlab_rails['db_encoding'] = 'utf8'
        external_url 'http://gitlab.local'
        gitlab_rails['terraform_state_enabled'] = false
        puma['enable'] = false
        gitlab_kas['enable'] = false
        grafana['enable'] = false
        gitaly['enable'] = false
    ports:
      - "8080:80"
      - "8043:443"
      - "8022:22"
    volumes:
      - config:/etc/gitlab
      - logs:/var/log/gitlab
      - data:/var/opt/gitlab
  postgresql:
    restart: always
    image: postgres:13.6-alpine
    container_name: gitlab-postgres
    environment:
      - POSTGRES_USER=gitlab
      - POSTGRES_PASSWORD=gitlab
      - POSTGRES_DB=gitlabhq_production
      - TZ=UTC
      - PGDATA=/data
    volumes:
      - dbdata:/data
    ports:
      - "5432:5432"

volumes:
  config:
  logs:
  data:
  dbdata: